spring.application.name=zomato-oms

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/zomato_oms
spring.datasource.username=postgres
spring.datasource.password=Mritunjay@123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true